"""add columns post, user and role

Revision ID: 01f797b6a966
Revises: 04a9e67c6ecb
Create Date: 2025-11-18 19:40:45.071650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01f797b6a966"
down_revision = "04a9e67c6ecb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.add_column(sa.Column("can_manage_users", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("can_manage_subscriptions", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(sa.Column("can_manage_posts", sa.Boolean(), nullable=True))
        batch_op.drop_column("cam_manage_subscriptions")
        batch_op.drop_column("cam_manage_users")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cam_manage_users", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "cam_manage_subscriptions",
                sa.BOOLEAN(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("can_manage_posts")
        batch_op.drop_column("can_manage_subscriptions")
        batch_op.drop_column("can_manage_users")

    # ### end Alembic commands ###
