"""add columns post, user and role

Revision ID: 0380cd23790d
Revises: 01f797b6a966
Create Date: 2025-11-18 19:47:25.890367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0380cd23790d"
down_revision = "01f797b6a966"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.add_column(sa.Column("can_create_posts", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("can_access_sensitive_information", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_column("can_access_sensitive_information")
        batch_op.drop_column("can_create_posts")

    # ### end Alembic commands ###
