"""empty message

Revision ID: 2439b908523d
Revises: 4220f20b2aaa
Create Date: 2025-11-19 12:51:15.846435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2439b908523d"
down_revision = "4220f20b2aaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.UnicodeText(), nullable=False))
        batch_op.add_column(sa.Column("excerpt", sa.UnicodeText(), nullable=False))
        batch_op.add_column(
            sa.Column("cover_url", sa.Unicode(length=1024), nullable=True)
        )
        batch_op.add_column(sa.Column("meta", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("content_md", sa.UnicodeText(), nullable=False))
        batch_op.drop_column("content")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("content_md")
        batch_op.drop_column("meta")
        batch_op.drop_column("cover_url")
        batch_op.drop_column("excerpt")
        batch_op.drop_column("slug")

    # ### end Alembic commands ###
