"""add columns post, user and role

Revision ID: 4220f20b2aaa
Revises: 974fb30024ae
Create Date: 2025-11-18 19:49:13.006305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4220f20b2aaa"
down_revision = "974fb30024ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.add_column(sa.Column("can_manage_roles", sa.Boolean(), nullable=True))
        batch_op.drop_column("can_create_roles")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "can_create_roles", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("can_manage_roles")

    # ### end Alembic commands ###
