"""empty message

Revision ID: 953d390ecedb
Revises: ce75151d95fc
Create Date: 2025-11-28 01:13:02.505085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "953d390ecedb"
down_revision = "ce75151d95fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("likes", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("likes")

    # ### end Alembic commands ###
