"""add columns post, user and role

Revision ID: 974fb30024ae
Revises: 0380cd23790d
Create Date: 2025-11-18 19:48:57.069367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974fb30024ae'
down_revision = '0380cd23790d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create_roles', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('can_create_roles')

    # ### end Alembic commands ###
