"""empty message

Revision ID: ce75151d95fc
Revises: 2439b908523d
Create Date: 2025-11-24 14:47:50.385464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce75151d95fc"
down_revision = "2439b908523d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["title"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar_url", sa.UnicodeText(), nullable=True))
        batch_op.add_column(
            sa.Column("public_title", sa.String(length=128), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("public_title")
        batch_op.drop_column("avatar_url")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
