tags = [
    # acadêmico geral
    "ensino fundamental",
    "ensino medio",
    "ensino medio tecnico",
    "primeiro ano ensino medio",
    "segundo ano ensino medio",
    "terceiro ano ensino medio",
    "escola publica",
    "escola particular",
    "estudante bolsista",
    "alto desempenho academico",
    "dificuldades em matematica",
    "dificuldades em exatas",
    "dificuldades em humanas",
    "gosta de estudar em grupo",
    "prefere estudar sozinho",

    # matemática
    "matematica iniciante",
    "matematica intermediario",
    "matematica avancado",
    "olimpiadas de matematica",
    "obmep",
    "imo",
    "resolucao de problemas",
    "algebra",
    "geometria",
    "teoria dos numeros",
    "combinatoria",
    "logica matematica",

    # ciências
    "fisica iniciante",
    "fisica intermediario",
    "fisica avancado",
    "quimica iniciante",
    "biologia iniciante",
    "astronomia",
    "ciencias naturais",
    "pesquisa cientifica",
    "iniciacao cientifica",
    "metodo cientifico",

    # tecnologia
    "programacao iniciante",
    "programacao intermediario",
    "programacao avancado",
    "python",
    "javascript",
    "web development",
    "backend",
    "frontend",
    "inteligencia artificial",
    "machine learning",
    "data science",
    "robotica",
    "algoritmos",
    "estrutura de dados",
    "open source",

    # olimpíadas científicas gerais
    "olimpiadas cientificas",
    "olimpiadas internacionais",
    "treinamento olimpico",
    "competicoes academicas",
    "listas de problemas",
    "simulados olimpicos",

    # vestibulares e provas
    "enem",
    "fuvest",
    "unicamp",
    "ime ita",
    "vestibulares militares",
    "preparacao para provas",
    "redacao",
    "interpretacao de texto",

    # exterior e oportunidades
    "exterior",
    "intercambio",
    "high school abroad",
    "summer programs",
    "programas internacionais",
    "bolsas de estudo",
    "financial aid",
    "full scholarship",
    "applications internacionais",
    "college application",
    "essay writing",
    "mentoria academica",

    # carreira e futuro
    "carreira em stem",
    "engenharia",
    "ciencia da computacao",
    "matematica pura",
    "pesquisa academica",
    "empreendedorismo",
    "startups",
    "impacto social",
    "lideranca jovem",
    "projetos sociais",

    # soft skills
    "comunicacao",
    "pensamento critico",
    "criatividade",
    "organizacao",
    "disciplina",
    "gestao do tempo",
    "autonomia",
    "resiliencia",
    "trabalho em equipe",
    "networking",

    # estilo de aprendizado
    "aprende com videos",
    "aprende lendo",
    "aprende ensinando",
    "aprende fazendo exercicios",
    "curioso",
    "autodidata",
    "gosta de desafios",
    "busca mentores",

    # contexto pessoal
    "primeira geracao na faculdade",
    "baixa renda",
    "zona rural",
    "cidade pequena",
    "sem apoio escolar",
    "sem cursinho",
    "estuda por conta propria",

    # idiomas
    "ingles basico",
    "ingles intermediario",
    "ingles avancado",
    "espanhol",
    "frances",
    "interesse em aprender idiomas",

    # conteúdo e engajamento
    "consome conteudo educacional",
    "cria conteudo educacional",
    "gosta de explicar",
    "participa de comunidades",
    "ativo em redes sociais",
    "embaixador educacional",
    "lider comunitario",

    # mentalidade
    "mentalidade de crescimento",
    "foco em longo prazo",
    "busca excelencia",
    "busca oportunidades",
    "sonha alto",
]
